language: node_js
node_js:
- node
before_install:
- bash shell/awscli.sh
jobs:
  include:
  - stage: Actualize
    if: type = api
    script:
    - rm -rf src/website/__tests__/__snapshots__
    - bash shell/regen.sh
    - bash shell/terraform.sh
    - bash shell/commit.sh
  - stage: Build
    if: type = push
    script:
    - bash shell/check.sh
    - npx gulp build
    - npx jest --collectCoverage
    - bash shell/package.sh
  - stage: Deploy
    if: ( type = push ) AND ( branch = master )
    install: skip
    script:
    - export REDIRECT_URL="https://${BUCKET}"
    deploy:
    - provider: s3
      bucket: $BUCKET
      local_dir: build/3/website
      acl: public_read
      skip_cleanup: true
    - provider: lambda
      function_name: $FUNCTION_NAME
      region: $AWS_DEFAULT_REGION
      role: $ROLE
      handler_name: handler
      module_name: index
      zip: build/dist.zip
      timeout: 300
      memory_size: 256
      runtime: nodejs8.10
      publish: true
      environment_variables:
      - CLIENT_ID=$CLIENT_ID
      - CLIENT_SECRET=$CLIENT_SECRET
      - DB_HOST=$DB_HOST
      - DB_NAME=$DB_NAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_PORT=$DB_PORT
      - DB_USERNAME=$DB_USERNAME
      - DEBUG=*
      - REDIRECT_URL=$REDIRECT_URL
      - SENTRY=$SENTRY
      skip_cleanup: true
  - stage: Verify
    if: type = pull_request
    script:
    - npx gulp build
    - "curl -H \"Authorization: token ${GITHUB_TOKEN}\" -X POST -d \"{\\\"body\\\": \\\"[Test build ${TRAVIS_BUILD_NUMBER}](https://to.do)\\\"}\" \"https://api.github.com/repos/${TRAVIS_REPO_SLUG}/issues/${TRAVIS_PULL_REQUEST}/comments\""
after_success:
- bash shell/awscli.sh
