language: node_js
node_js:
- node
cache: yarn
before_script:
- ./refresh
script:
- yarn test
- yarn build
before_deploy:
- rm -rf node_modules
- yarn install --prod
- yarn prepare-remote
- mv _bin/server/index.js index.js
- zip -r prod.zip node_modules index.js
deploy:
  - provider: s3
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $SECRET_ACCESS_KEY
    bucket: $BUCKET
    region: $REGION
    local_dir: _bin/client
    acl: public_read
    skip_cleanup: true
    on:
      branch: master
  - provider: lambda
    function_name: $FUNCTION_NAME
    region: $REGION
    role: $ROLE
    runtime: nodejs8.1
    handler_name: handler
    zip_file: prod.zip
    skip_cleanup: true
    on:
      branch: master
