language: node_js
node_js:
- node
install: bash shell/install.sh
cache: yarn
jobs:
  include:
  - stage: Actualize
    if: type = api
    script: bash shell/trigger.sh
  - stage: Test
    if: ( type = push ) AND ( branch != master )
    script: bash shell/push.sh
  - stage: Deploy
    if: ( type = push ) AND ( branch = master )
    script: bash shell/master.sh
  - stage: Verify
    if: type = pull_request
    script: bash shell/pr.sh
