language: node_js
node_js:
- node
cache: yarn
before_script:
- ./setup.sh
script:
- yarn build
before_deploy:
- if [[ -z "$TRAVIS_TAG" ]] ; then cp .robots.txt _bin/client/robots.txt ; fi
- git add -f _bin
- git rm -r src
deploy:
  - provider: elasticbeanstalk
    skip_cleanup: true
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: $AWS_REGION
    app: $AWS_APP
    env: $AWS_ENV_BETA
    bucket_name: $AWS_BUCKET_NAME
    on:
      branch: master
  - provider: elasticbeanstalk
    skip_cleanup: true
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $SECRET_ACCESS_KEY
    region: AWS_REGION
    app: $AWS_APP
    env: $AWS_ENV_PROD
    bucket_name: $AWS_BUCKET_NAME
    on:
      tags: true
      condition: "$TRAVIS_TAG =~ ^v[0-9]+$"
