language: node_js
node_js:
- node
cache:
  yarn: true
  directories:
  - ~/.flow-typed
  - flow-typed
  - node_modules
  - node_modules_prod
before_script:
- yarn gulp flow-typed
script:
- yarn test
- yarn build
before_cache:
- yarn install --prod --modules-folder node_modules_prod
after_success:
- rm -rf node_modules
- mv node_modules_prod node_modules
- mv _bin/client/index.remote.js _bin/client/index.js
- rm _bin/client/index.local.js
- if [[ -z "$TRAVIS_TAG" ]] ; then cp src/client/static/robots.txt _bin/client/robots.txt ; fi
- mv _bin/server/index.remote.js index.js
- mv _bin/server/schema.graphql schema.graphql
- zip -q -r dist.zip node_modules index.js schema.graphql
deploy:
  - provider: s3
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $SECRET_ACCESS_KEY
    bucket: $BUCKET_BETA
    region: $REGION
    local_dir: _bin/client
    acl: public_read
    skip_cleanup: true
    on:
      branch: master
  - provider: lambda
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $SECRET_ACCESS_KEY
    region: $REGION
    function_name: $FUNCTION_NAME_BETA
    role: $ROLE
    handler_name: handler
    module_name: index
    zip: dist.zip
    timeout: 300
    memory_size: 256
    runtime: nodejs8.10
    publish: true
    environment_variables:
    - CLIENT_ID=$CLIENT_ID
    - CLIENT_SECRET=$CLIENT_SECRET
    - DB_HOST=$DB_HOST
    - DB_NAME=$DB_NAME
    - DB_PASSWORD=$DB_PASSWORD
    - DB_PORT=$DB_PORT
    - DB_USERNAME=$DB_USERNAME
    - DEBUG=*
    - REDIRECT_URL=$REDIRECT_URL_BETA
    function_tags:
    - Name=$FUNCTION_NAME
    skip_cleanup: true
    on:
      branch: master
  - provider: s3
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $SECRET_ACCESS_KEY
    bucket: $BUCKET
    region: $REGION
    local_dir: _bin/client
    acl: public_read
    skip_cleanup: true
    on:
      tags: true
      condition: "$TRAVIS_TAG =~ ^v[0-9]+$"
  - provider: lambda
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $SECRET_ACCESS_KEY
    region: $REGION
    function_name: $FUNCTION_NAME
    role: $ROLE
    handler_name: handler
    module_name: index
    zip: dist.zip
    timeout: 300
    memory_size: 256
    runtime: nodejs8.10
    publish: true
    environment_variables:
    - CLIENT_ID=$CLIENT_ID
    - CLIENT_SECRET=$CLIENT_SECRET
    - DB_HOST=$DB_HOST
    - DB_NAME=$DB_NAME
    - DB_PASSWORD=$DB_PASSWORD
    - DB_PORT=$DB_PORT
    - DB_USERNAME=$DB_USERNAME
    - DEBUG=*
    - REDIRECT_URL=$REDIRECT_URL
    function_tags:
    - Name=$FUNCTION_NAME
    skip_cleanup: true
    on:
      tags: true
      condition: "$TRAVIS_TAG =~ ^v[0-9]+$"
