env:
  global:
  - PATH=$HOME/.local/bin:$PATH
language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
  - .cache/pip
before_install:
- export AWS_ACCESS_KEY_ID=$ACCESS_KEY_ID
- export AWS_SECRET_ACCESS_KEY=$SECRET_ACCESS_KEY
- export AWS_DEFAULT_REGION=$REGION
- pip install --user awscli
- mkdir build
- aws s3 sync s3://$BUCKET_BUILD/$TRAVIS_BUILD_NUMBER build
jobs:
  include:
  - stage: Lint & Build
    script:
    - npm run build:0
  - script:
    - npm run build:1
    - npm run build:2
  - stage: Test & Package
    script:
    - npm run test
  - script
    - npm run build:3
    - if [[ "$TRAVIS_TAG" ]] ; then rm build/3/website/static/robots.txt ; fi
    - npm prune --production
    - cp build/3/server/index.js index.js
    - cp build/3/server/schema.graphql schema.graphql
    - zip -q -r build/dist.zip node_modules index.js schema.graphql
  - stage: Deploy
    script: skip
    deploy:
    - provider: s3
      bucket: $BUCKET_BETA
      local_dir: build/3/website
      acl: public_read
      skip_cleanup: true
      on:
        branch: master
    - provider: lambda
      function_name: $FUNCTION_NAME_BETA
      role: $ROLE
      handler_name: handler
      module_name: index
      zip: dist.zip
      timeout: 300
      memory_size: 256
      runtime: nodejs8.10
      publish: true
      environment_variables:
      - CLIENT_ID=$CLIENT_ID
      - CLIENT_SECRET=$CLIENT_SECRET
      - DB_HOST=$DB_HOST
      - DB_NAME=$DB_NAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_PORT=$DB_PORT
      - DB_USERNAME=$DB_USERNAME
      - DEBUG=*
      - ENV=BETA
      - REDIRECT_URL=$REDIRECT_URL_BETA
      - SENTRY=$SENTRY
      function_tags:
      - Name=$FUNCTION_NAME
      skip_cleanup: true
      on:
        branch: master
    - provider: s3
      bucket: $BUCKET
      local_dir: build/3/website
      acl: public_read
      skip_cleanup: true
      on:
        tags: true
        condition: "$TRAVIS_TAG =~ ^v[0-9]+$"
    - provider: lambda
      function_name: $FUNCTION_NAME
      role: $ROLE
      handler_name: handler
      module_name: index
      zip: dist.zip
      timeout: 300
      memory_size: 256
      runtime: nodejs8.10
      publish: true
      environment_variables:
      - CLIENT_ID=$CLIENT_ID
      - CLIENT_SECRET=$CLIENT_SECRET
      - DB_HOST=$DB_HOST
      - DB_NAME=$DB_NAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_PORT=$DB_PORT
      - DB_USERNAME=$DB_USERNAME
      - DEBUG=*
      - ENV=PROD
      - REDIRECT_URL=$REDIRECT_URL
      - SENTRY=$SENTRY
      function_tags:
      - Name=$FUNCTION_NAME
      skip_cleanup: true
      on:
        tags: true
        condition: "$TRAVIS_TAG =~ ^v[0-9]+$"
after_success:
- aws s3 sync build s3://$BUCKET_BUILD/$TRAVIS_BUILD_NUMBER
