language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
script:
- npm run build
- npm run test
after_success:
- rm -rf node_modules
- npm install --only=production
- if [[ "$TRAVIS_TAG" ]] ; then rm _build_3/website/static/robots.txt ; fi
- cp _build_3/server/index.js index.js
- cp _build_3/server/schema.graphql schema.graphql
- zip -q -r dist.zip node_modules index.js schema.graphql
deploy:
  - provider: s3
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $SECRET_ACCESS_KEY
    bucket: $BUCKET_BETA
    region: $REGION
    local_dir: _build_3/website
    acl: public_read
    skip_cleanup: true
    on:
      branch: master
  - provider: lambda
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $SECRET_ACCESS_KEY
    region: $REGION
    function_name: $FUNCTION_NAME_BETA
    role: $ROLE
    handler_name: handler
    module_name: index
    zip: dist.zip
    timeout: 300
    memory_size: 256
    runtime: nodejs8.10
    publish: true
    environment_variables:
    - CLIENT_ID=$CLIENT_ID
    - CLIENT_SECRET=$CLIENT_SECRET
    - DB_HOST=$DB_HOST
    - DB_NAME=$DB_NAME
    - DB_PASSWORD=$DB_PASSWORD
    - DB_PORT=$DB_PORT
    - DB_USERNAME=$DB_USERNAME
    - DEBUG=*
    - ENV=BETA
    - REDIRECT_URL=$REDIRECT_URL_BETA
    function_tags:
    - Name=$FUNCTION_NAME
    skip_cleanup: true
    on:
      branch: master
  - provider: s3
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $SECRET_ACCESS_KEY
    bucket: $BUCKET
    region: $REGION
    local_dir: _build_3/website
    acl: public_read
    skip_cleanup: true
    on:
      tags: true
      condition: "$TRAVIS_TAG =~ ^v[0-9]+$"
  - provider: lambda
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $SECRET_ACCESS_KEY
    region: $REGION
    function_name: $FUNCTION_NAME
    role: $ROLE
    handler_name: handler
    module_name: index
    zip: dist.zip
    timeout: 300
    memory_size: 256
    runtime: nodejs8.10
    publish: true
    environment_variables:
    - CLIENT_ID=$CLIENT_ID
    - CLIENT_SECRET=$CLIENT_SECRET
    - DB_HOST=$DB_HOST
    - DB_NAME=$DB_NAME
    - DB_PASSWORD=$DB_PASSWORD
    - DB_PORT=$DB_PORT
    - DB_USERNAME=$DB_USERNAME
    - DEBUG=*
    - ENV=PROD
    - REDIRECT_URL=$REDIRECT_URL
    function_tags:
    - Name=$FUNCTION_NAME
    skip_cleanup: true
    on:
      tags: true
      condition: "$TRAVIS_TAG =~ ^v[0-9]+$"
