language: node_js
node_js:
- node
install: bash shell/install.sh
cache: yarn
jobs:
  include:
  - stage: Actualize
    if: type = api
    script: bash shell/actualize.sh
  - stage: Test
    if: ( type = push ) AND ( branch != master )
    script: bash shell/test.sh
  - stage: Deploy
    if: ( type = push ) AND ( branch = master )
    script: bash shell/deploy.sh
  - stage: Verify
    if: type = pull_request
    script: bash shell/verify.sh
