language: node_js
node_js:
- node
install: bash shell/install.sh
cache: yarn
env:
script: ignore
matrix:
  fast_finish: true
  allow_failures:
  - env: L8R=TRUE
jobs:
  include:
  - stage: Trigger
    if: type IN (api, cron)
    script: bash shell/trigger.sh
  - stage: Push
    if: ( type = push ) AND ( branch != master )
    script: bash shell/push.sh
  - stage: Master
    if: ( type = push ) AND ( branch = master )
    script: bash shell/master.sh
  - stage: Pull request
    if: type = pull_request
    script: bash shell/pr.sh
  - stage: Cron
    env: L8R=TRUE
    if: type IN (api, cron)
    script: bash shell/cron.sh
