language: node_js
node_js:
- node
cache: yarn
before_script:
- ./refresh
script:
- yarn build
deploy:
  - provider: s3
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $SECRET_ACCESS_KEY
    bucket: $BUCKET
    region: $REGION
    local_dir: _bin/client
    acl: public_read
    on:
      branch: master
