language: node_js
node_js:
- node
cache: yarn
before_script:
- yarn clean
script:
- yarn build
- mv _bin/client/index.remote.js _bin/client/index.js
- rm _bin/client/index.local.js
- mv _bin/server/index.remote.js index.js
- mv _bin/server/schema.graphql schema.graphql
- rm -rf node_modules
- yarn install --prod
- zip -r prod.zip node_modules index.js schema.graphql
deploy:
  - provider: s3
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $SECRET_ACCESS_KEY
    bucket: $BUCKET
    region: $REGION
    local_dir: _bin/client
    acl: public_read
    skip_cleanup: true
    on:
      branch: master
  - provider: lambda
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $SECRET_ACCESS_KEY
    function_name: $FUNCTION_NAME
    region: $REGION
    role: $ROLE
    runtime: nodejs8.10
    handler_name: handler
    zip: prod.zip
    timeout: 300
    memory_size: 512
    publish: true
    environment_variables:
    - CLIENT_ID=$CLIENT_ID
    - CLIENT_SECRET=$CLIENT_SECRET
    - DB_HOST=$DB_HOST
    - DB_NAME=$DB_NAME
    - DB_PASSWORD=$DB_PASSWORD
    - DB_PORT=$DB_PORT
    - DB_USERNAME=$DB_USERNAME
    - DEBUG=*
    - REDIRECT_URL=$REDIRECT_URL
    function_tags:
    - NAME=$FUNCTION_NAME
    skip_cleanup: true
    on:
      branch: master
