on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@master
    - name: Test Deploy
      run: |
        npm install --global --upgrade yarn
        yarn install
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_VAULT_TOKEN: ${{ secrets.TF_VAR_VAULT_TOKEN }}
        TF_VAR_DOMAIN: opinionated.baby
        TF_VAR_NAME: opinionatedbaby
